version: '3'
services:
  server:
    image: swe-server:latest
    ports:
    - "8080:8080"
    links:
    - psql
    depends_on:
    - psql
    volumes:
    - ./dhbw_swe_react/build:/static
    networks:
    - backend
    - frontend
  psql:
    image: postgres:10-alpine
    environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_USER=admin
    - POSTGRES_DB=store
    networks:
    - backend
networks: 
  frontend:
    internal: false 
  backend:
    internal: true