version: '3'
services:
  server:
    image: swe-server:latest
    ports:
    - "8080:8080"
    links:
    - psql
    depends_on:
    - psql
    volumes:
    - ./tmp
  psql:
    image: postgres:10-alpine
    ports:
    - "5432:5432"
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_USER=admin