version: '3'
services:
  node:
    image: node:alpine
    environment:
      - NODE_ENV=production
    volumes:
    - ./dhbw_swe_react:/home/node
    - ./logs/node:/root/.npm/_logs
    command: sh -c "cp -r /home/node /home/work && cd /home/work && npm install && npm run build && cp -Lrf /home/work /home/node"
  server:
    image: swe-server:latest
    ports:
    - "8080:8080"
    links:
    - psql
    depends_on:
    - psql
    volumes:
    - ./dhbw_swe_react/build:/static
  psql:
    image: postgres:10-alpine
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_USER=admin
    - POSTGRES_DB=store